# Generated by Django 4.1.1 on 2022-10-02 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistrationInfo",
            fields=[
                ("application_id", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date_of_birth", models.DateField()),
                ("position", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name=uuid.uuid4,
                    ),
                ),
                ("ward", models.IntegerField()),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("R", "Recieved"),
                            ("DDLG", "DDLG"),
                            ("P", "Ready for Print"),
                            ("D", "Ready for Delivery"),
                            ("Dd", "Delivered"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("B", "Bengali"), ("E", "English")], max_length=20
                    ),
                ),
            ],
        ),
    ]
