# Generated by Django 4.1.1 on 2022-10-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationinfo",
            name="application_online_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
