# Generated by Django 4.1.1 on 2022-10-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0002_registrationinfo_application_online_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationinfo",
            name="comments",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="registrationinfo",
            name="position",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registrationinfo",
            name="type",
            field=models.CharField(
                choices=[("B", "Bengali"), ("E", "English"), ("BE", "Both")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="registrationinfo",
            name="ward",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
