# Generated by Django 4.1.1 on 2022-10-02 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0003_registrationinfo_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationinfo",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
